services:
  - type: web
    name: faculty-analyzer2
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install -r requirements-render.txt
    startCommand: bash start_render.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: USE_GOOGLE_SCHOLAR
        value: "false"
