services:
  - type: web
    name: faculty-analyzer2
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install -r requirements-render.txt
    startCommand: cd Publication_Analyzer/Publication_Analyzer && gunicorn backend.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: USE_GOOGLE_SCHOLAR
        value: "false"
