services:
  - type: web
    name: faculty-analyzer2
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: cd Publication_Analyzer/Publication_Analyzer && gunicorn backend.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HUGGINGFACE_API_KEY
        sync: false
